import io
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, Image, PageBreak
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib import colors

from .pdf_styles import (
    PRIMARY, SECONDARY, ACCENT, POSITIVE, NEGATIVE, BG_LIGHT, BORDER,
    HEADER_TABLE_STYLE, SIMPLE_TABLE_STYLE,
    fmt_currency, fmt_pct, fmt_multiple, fmt_price,
)
from .pdf_chart_renderer import render_waterfall_chart, render_football_field


class ModelPDFService:
    """Generates a 4-page PDF valuation report."""

    async def generate(self, ticker, model_type, assumptions, engine_result, current_price):
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch,
            leftMargin=0.75*inch,
            rightMargin=0.75*inch,
        )

        self._ticker = ticker
        self._model_type = model_type
        self._date = datetime.now().strftime('%Y-%m-%d')

        styles = getSampleStyleSheet()
        self._styles = styles
        self._title_style = ParagraphStyle('Title2', parent=styles['Title'], fontSize=18, textColor=PRIMARY, spaceAfter=6)
        self._subtitle_style = ParagraphStyle('Subtitle2', parent=styles['Normal'], fontSize=10, textColor=SECONDARY, spaceAfter=12)
        self._heading_style = ParagraphStyle('Heading2', parent=styles['Heading2'], fontSize=12, textColor=PRIMARY, spaceBefore=12, spaceAfter=6)
        self._body_style = ParagraphStyle('Body2', parent=styles['Normal'], fontSize=9, textColor=PRIMARY, leading=12)
        self._big_value_style = ParagraphStyle('BigValue', parent=styles['Normal'], fontSize=24, fontName='Helvetica-Bold', textColor=ACCENT, alignment=TA_CENTER, spaceAfter=4)
        self._label_style = ParagraphStyle('Label2', parent=styles['Normal'], fontSize=8, textColor=SECONDARY, alignment=TA_CENTER)

        story = []
        story += self._page1_executive_summary(assumptions, engine_result, current_price)
        story.append(PageBreak())
        story += self._page2_assumptions(assumptions)
        story.append(PageBreak())
        story += self._page3_projections(engine_result)
        story.append(PageBreak())
        story += self._page4_valuation(engine_result, current_price)

        doc.build(story, onFirstPage=self._header_footer, onLaterPages=self._header_footer)
        buffer.seek(0)
        return buffer.getvalue()

    def _header_footer(self, canvas, doc):
        canvas.saveState()
        # Header
        canvas.setFont('Helvetica', 7)
        canvas.setFillColor(SECONDARY)
        canvas.drawString(doc.leftMargin, doc.height + doc.topMargin - 10,
                         f"{self._ticker} — {self._model_type.upper()} Valuation Report — {self._date}")
        canvas.drawRightString(doc.width + doc.leftMargin, doc.height + doc.topMargin - 10,
                              f"Page {canvas.getPageNumber()}")
        # Footer
        canvas.drawString(doc.leftMargin, 0.5*inch,
                         f"Generated by Finance App · Not investment advice · {self._date}")
        canvas.restoreState()

    def _page1_executive_summary(self, assumptions, engine_result, current_price):
        elements = []
        elements.append(Paragraph("VALUATION REPORT", self._title_style))
        elements.append(Paragraph(f"{self._ticker} — {self._model_type.upper()} Model", self._subtitle_style))
        elements.append(Spacer(1, 12))

        # Intrinsic value
        base = engine_result.get('scenarios', {}).get('base', {})
        implied = base.get('implied_price', engine_result.get('weighted_implied_price', 0))
        upside = ((implied / current_price) - 1) * 100 if current_price else 0

        elements.append(Paragraph(fmt_price(implied), self._big_value_style))
        elements.append(Paragraph("Intrinsic Value (Base Case)", self._label_style))
        elements.append(Spacer(1, 6))

        color = 'green' if upside > 0 else 'red'
        sign = '+' if upside > 0 else ''
        elements.append(Paragraph(
            f'Current: {fmt_price(current_price)} | <font color="{color}">{sign}{upside:.1f}% upside</font>',
            ParagraphStyle('UpsideStyle', parent=self._body_style, alignment=TA_CENTER, fontSize=10)
        ))
        elements.append(Spacer(1, 18))

        # Scenario summary table
        elements.append(Paragraph("Scenario Summary", self._heading_style))
        table_data = [["Scenario", "Implied Price", "Weight", "Upside"]]
        for name in ['bear', 'base', 'bull']:
            sc = engine_result.get('scenarios', {}).get(name, {})
            if not sc:
                continue
            sc_upside = sc.get('upside_downside_pct')
            table_data.append([
                name.capitalize(),
                fmt_price(sc.get('implied_price', 0)),
                fmt_pct(sc.get('scenario_weight', 0)),
                fmt_pct(sc_upside / 100 if sc_upside else 0) if sc_upside is not None else '--',
            ])
        if len(table_data) > 1:
            t = Table(table_data, colWidths=[1.5*inch, 1.5*inch, 1*inch, 1*inch])
            t.setStyle(HEADER_TABLE_STYLE)
            elements.append(t)
        elements.append(Spacer(1, 12))

        # Key assumptions
        elements.append(Paragraph("Key Assumptions", self._heading_style))
        dcf_a = assumptions.get('model_assumptions', {}).get('dcf', {})
        ka_data = [
            ["WACC", fmt_pct(dcf_a.get('wacc', 0))],
            ["Terminal Growth", fmt_pct(dcf_a.get('terminal_growth_rate', 0))],
            ["Tax Rate", fmt_pct(dcf_a.get('tax_rate', 0))],
            ["Projection Years", str(dcf_a.get('projection_years', 10))],
        ]
        t = Table(ka_data, colWidths=[2.5*inch, 1.5*inch])
        t.setStyle(SIMPLE_TABLE_STYLE)
        elements.append(t)
        elements.append(Spacer(1, 12))

        # Waterfall chart
        waterfall = engine_result.get('waterfall', {}).get('steps', [])
        if waterfall:
            elements.append(Paragraph("Valuation Waterfall", self._heading_style))
            chart_bytes = render_waterfall_chart(waterfall)
            img = Image(io.BytesIO(chart_bytes), width=5.5*inch, height=3*inch)
            elements.append(img)

        return elements

    def _page2_assumptions(self, assumptions):
        elements = []
        elements.append(Paragraph("KEY ASSUMPTIONS", self._title_style))
        elements.append(Spacer(1, 12))

        dcf_a = assumptions.get('model_assumptions', {}).get('dcf', {})
        reasoning = assumptions.get('reasoning', {})

        # Parameters section
        elements.append(Paragraph("Model Parameters", self._heading_style))
        params = [
            ["Parameter", "Value", "Source"],
            ["WACC", fmt_pct(dcf_a.get('wacc')), "Engine"],
            ["Terminal Growth Rate", fmt_pct(dcf_a.get('terminal_growth_rate')), "Engine"],
            ["Tax Rate", fmt_pct(dcf_a.get('tax_rate')), "Engine"],
            ["CapEx % of Revenue", fmt_pct(dcf_a.get('capex_to_revenue')), "Engine"],
            ["NWC % of Revenue", fmt_pct(dcf_a.get('nwc_pct_of_revenue')), "Engine"],
            ["D&A % of Revenue", fmt_pct(dcf_a.get('da_pct_of_revenue')), "Engine"],
        ]
        t = Table(params, colWidths=[2.5*inch, 1.5*inch, 1.5*inch])
        t.setStyle(HEADER_TABLE_STYLE)
        elements.append(t)
        elements.append(Spacer(1, 12))

        # Growth rates
        growth_rates = dcf_a.get('revenue_growth_rates', [])
        if growth_rates:
            elements.append(Paragraph("Revenue Growth Rates", self._heading_style))
            gr_data = [["Year", "Growth Rate"]]
            for i, rate in enumerate(growth_rates):
                gr_data.append([f"Year {i+1}", fmt_pct(rate)])
            t = Table(gr_data, colWidths=[2*inch, 1.5*inch])
            t.setStyle(HEADER_TABLE_STYLE)
            elements.append(t)
            elements.append(Spacer(1, 12))

        # Operating margins
        margins = dcf_a.get('operating_margins', [])
        if margins:
            elements.append(Paragraph("Operating Margins", self._heading_style))
            m_data = [["Year", "Margin"]]
            for i, m in enumerate(margins):
                m_data.append([f"Year {i+1}", fmt_pct(m)])
            t = Table(m_data, colWidths=[2*inch, 1.5*inch])
            t.setStyle(HEADER_TABLE_STYLE)
            elements.append(t)
            elements.append(Spacer(1, 12))

        # Reasoning
        if reasoning:
            elements.append(Paragraph("Assumption Reasoning", self._heading_style))
            for key, text in reasoning.items():
                elements.append(Paragraph(f"<b>{key}:</b> {text}", self._body_style))
                elements.append(Spacer(1, 4))

        return elements

    def _page3_projections(self, engine_result):
        elements = []
        elements.append(Paragraph("PROJECTION TABLE", self._title_style))
        elements.append(Spacer(1, 12))

        base = engine_result.get('scenarios', {}).get('base', {})
        proj = base.get('projection_table', [])
        if not proj:
            elements.append(Paragraph("No projection data available.", self._body_style))
            return elements

        # Build table
        line_items = [
            ("Revenue", "revenue", fmt_currency),
            ("Rev Growth", "revenue_growth", fmt_pct),
            ("Gross Profit", "gross_profit", fmt_currency),
            ("Gross Margin", "gross_margin", fmt_pct),
            ("EBIT", "ebit", fmt_currency),
            ("Op Margin", "operating_margin", fmt_pct),
            ("EBITDA", "ebitda", fmt_currency),
            ("NOPAT", "nopat", fmt_currency),
            ("FCF", "fcf", fmt_currency),
            ("FCF Margin", "fcf_margin", fmt_pct),
            ("PV of FCF", "pv_fcf", fmt_currency),
        ]

        # Header
        years = [str(yr.get('year', '')) for yr in proj]
        header = [""] + years
        table_data = [header]

        for label, key, formatter in line_items:
            row = [label]
            for yr in proj:
                val = yr.get(key, 0)
                row.append(formatter(val) if val is not None else '--')
            table_data.append(row)

        col_width = min(0.85 * inch, (6.5 * inch) / (len(years) + 1))
        col_widths = [1.2 * inch] + [col_width] * len(years)
        t = Table(table_data, colWidths=col_widths)
        t.setStyle(HEADER_TABLE_STYLE)
        elements.append(t)

        return elements

    def _page4_valuation(self, engine_result, current_price):
        elements = []
        elements.append(Paragraph("VALUATION OUTPUT", self._title_style))
        elements.append(Spacer(1, 12))

        base = engine_result.get('scenarios', {}).get('base', {})

        # Waterfall detail
        elements.append(Paragraph("Valuation Bridge", self._heading_style))
        bridge_data = [
            ["Component", "Value"],
            ["PV of FCFs", fmt_currency(base.get('pv_fcf_total', 0))],
            ["PV Terminal Value", fmt_currency(base.get('pv_terminal_value', 0))],
            ["Enterprise Value", fmt_currency(base.get('enterprise_value', 0))],
            ["Equity Value", fmt_currency(base.get('equity_value', 0))],
            ["Implied Price/Share", fmt_price(base.get('implied_price', 0))],
        ]
        t = Table(bridge_data, colWidths=[3*inch, 2*inch])
        t.setStyle(HEADER_TABLE_STYLE)
        elements.append(t)
        elements.append(Spacer(1, 6))

        tv_pct = base.get('tv_pct_of_ev', 0)
        elements.append(Paragraph(f"Terminal Value as % of EV: {fmt_pct(tv_pct)}", self._body_style))
        elements.append(Spacer(1, 18))

        # Football field chart
        ff = engine_result.get('football_field', {})
        ff_ranges = ff.get('ranges', []) if isinstance(ff, dict) else []
        if ff_ranges:
            elements.append(Paragraph("Valuation Range (Football Field)", self._heading_style))
            chart_bytes = render_football_field(
                [r if isinstance(r, dict) else {} for r in ff_ranges],
                current_price
            )
            img = Image(io.BytesIO(chart_bytes), width=5.5*inch, height=2.2*inch)
            elements.append(img)

        return elements
